/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiVersion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiAbout
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiAbout {
  @SerializedName("app")
  private String app = null;

  @SerializedName("auths")
  private List<String> auths = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("uptime_seconds")
  private Integer uptimeSeconds = null;

  @SerializedName("version")
  private ApiVersion version = null;

  public ApiAbout app(String app) {
    this.app = app;
    return this;
  }

   /**
   * Get app
   * @return app
  **/
  @ApiModelProperty(value = "")
  public String getApp() {
    return app;
  }

  public void setApp(String app) {
    this.app = app;
  }

  public ApiAbout auths(List<String> auths) {
    this.auths = auths;
    return this;
  }

  public ApiAbout addAuthsItem(String authsItem) {
    if (this.auths == null) {
      this.auths = new ArrayList<String>();
    }
    this.auths.add(authsItem);
    return this;
  }

   /**
   * Get auths
   * @return auths
  **/
  @ApiModelProperty(value = "")
  public List<String> getAuths() {
    return auths;
  }

  public void setAuths(List<String> auths) {
    this.auths = auths;
  }

  public ApiAbout createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ApiAbout id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiAbout name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApiAbout uptimeSeconds(Integer uptimeSeconds) {
    this.uptimeSeconds = uptimeSeconds;
    return this;
  }

   /**
   * Get uptimeSeconds
   * @return uptimeSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getUptimeSeconds() {
    return uptimeSeconds;
  }

  public void setUptimeSeconds(Integer uptimeSeconds) {
    this.uptimeSeconds = uptimeSeconds;
  }

  public ApiAbout version(ApiVersion version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public ApiVersion getVersion() {
    return version;
  }

  public void setVersion(ApiVersion version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiAbout apiAbout = (ApiAbout) o;
    return Objects.equals(this.app, apiAbout.app) &&
        Objects.equals(this.auths, apiAbout.auths) &&
        Objects.equals(this.createdAt, apiAbout.createdAt) &&
        Objects.equals(this.id, apiAbout.id) &&
        Objects.equals(this.name, apiAbout.name) &&
        Objects.equals(this.uptimeSeconds, apiAbout.uptimeSeconds) &&
        Objects.equals(this.version, apiAbout.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, auths, createdAt, id, name, uptimeSeconds, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiAbout {\n");
    
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    auths: ").append(toIndentedString(auths)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uptimeSeconds: ").append(toIndentedString(uptimeSeconds)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

