/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiConfigData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiConfigData {
  @SerializedName("address")
  private String address = null;

  @SerializedName("api")
  private Object api = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("db")
  private Object db = null;

  @SerializedName("debug")
  private Object debug = null;

  @SerializedName("ffmpeg")
  private Object ffmpeg = null;

  @SerializedName("host")
  private Object host = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("log")
  private Object log = null;

  @SerializedName("metrics")
  private Object metrics = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("playout")
  private Object playout = null;

  @SerializedName("router")
  private Object router = null;

  @SerializedName("rtmp")
  private Object rtmp = null;

  @SerializedName("service")
  private Object service = null;

  @SerializedName("sessions")
  private Object sessions = null;

  @SerializedName("storage")
  private Object storage = null;

  @SerializedName("tls")
  private Object tls = null;

  @SerializedName("update_check")
  private Boolean updateCheck = null;

  @SerializedName("version")
  private Integer version = null;

  public ApiConfigData address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ApiConfigData api(Object api) {
    this.api = api;
    return this;
  }

   /**
   * Get api
   * @return api
  **/
  @ApiModelProperty(value = "")
  public Object getApi() {
    return api;
  }

  public void setApi(Object api) {
    this.api = api;
  }

  public ApiConfigData createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ApiConfigData db(Object db) {
    this.db = db;
    return this;
  }

   /**
   * Get db
   * @return db
  **/
  @ApiModelProperty(value = "")
  public Object getDb() {
    return db;
  }

  public void setDb(Object db) {
    this.db = db;
  }

  public ApiConfigData debug(Object debug) {
    this.debug = debug;
    return this;
  }

   /**
   * Get debug
   * @return debug
  **/
  @ApiModelProperty(value = "")
  public Object getDebug() {
    return debug;
  }

  public void setDebug(Object debug) {
    this.debug = debug;
  }

  public ApiConfigData ffmpeg(Object ffmpeg) {
    this.ffmpeg = ffmpeg;
    return this;
  }

   /**
   * Get ffmpeg
   * @return ffmpeg
  **/
  @ApiModelProperty(value = "")
  public Object getFfmpeg() {
    return ffmpeg;
  }

  public void setFfmpeg(Object ffmpeg) {
    this.ffmpeg = ffmpeg;
  }

  public ApiConfigData host(Object host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(value = "")
  public Object getHost() {
    return host;
  }

  public void setHost(Object host) {
    this.host = host;
  }

  public ApiConfigData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiConfigData log(Object log) {
    this.log = log;
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  @ApiModelProperty(value = "")
  public Object getLog() {
    return log;
  }

  public void setLog(Object log) {
    this.log = log;
  }

  public ApiConfigData metrics(Object metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public Object getMetrics() {
    return metrics;
  }

  public void setMetrics(Object metrics) {
    this.metrics = metrics;
  }

  public ApiConfigData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApiConfigData playout(Object playout) {
    this.playout = playout;
    return this;
  }

   /**
   * Get playout
   * @return playout
  **/
  @ApiModelProperty(value = "")
  public Object getPlayout() {
    return playout;
  }

  public void setPlayout(Object playout) {
    this.playout = playout;
  }

  public ApiConfigData router(Object router) {
    this.router = router;
    return this;
  }

   /**
   * Get router
   * @return router
  **/
  @ApiModelProperty(value = "")
  public Object getRouter() {
    return router;
  }

  public void setRouter(Object router) {
    this.router = router;
  }

  public ApiConfigData rtmp(Object rtmp) {
    this.rtmp = rtmp;
    return this;
  }

   /**
   * Get rtmp
   * @return rtmp
  **/
  @ApiModelProperty(value = "")
  public Object getRtmp() {
    return rtmp;
  }

  public void setRtmp(Object rtmp) {
    this.rtmp = rtmp;
  }

  public ApiConfigData service(Object service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  @ApiModelProperty(value = "")
  public Object getService() {
    return service;
  }

  public void setService(Object service) {
    this.service = service;
  }

  public ApiConfigData sessions(Object sessions) {
    this.sessions = sessions;
    return this;
  }

   /**
   * Get sessions
   * @return sessions
  **/
  @ApiModelProperty(value = "")
  public Object getSessions() {
    return sessions;
  }

  public void setSessions(Object sessions) {
    this.sessions = sessions;
  }

  public ApiConfigData storage(Object storage) {
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @ApiModelProperty(value = "")
  public Object getStorage() {
    return storage;
  }

  public void setStorage(Object storage) {
    this.storage = storage;
  }

  public ApiConfigData tls(Object tls) {
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @ApiModelProperty(value = "")
  public Object getTls() {
    return tls;
  }

  public void setTls(Object tls) {
    this.tls = tls;
  }

  public ApiConfigData updateCheck(Boolean updateCheck) {
    this.updateCheck = updateCheck;
    return this;
  }

   /**
   * Get updateCheck
   * @return updateCheck
  **/
  @ApiModelProperty(value = "")
  public Boolean isUpdateCheck() {
    return updateCheck;
  }

  public void setUpdateCheck(Boolean updateCheck) {
    this.updateCheck = updateCheck;
  }

  public ApiConfigData version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiConfigData apiConfigData = (ApiConfigData) o;
    return Objects.equals(this.address, apiConfigData.address) &&
        Objects.equals(this.api, apiConfigData.api) &&
        Objects.equals(this.createdAt, apiConfigData.createdAt) &&
        Objects.equals(this.db, apiConfigData.db) &&
        Objects.equals(this.debug, apiConfigData.debug) &&
        Objects.equals(this.ffmpeg, apiConfigData.ffmpeg) &&
        Objects.equals(this.host, apiConfigData.host) &&
        Objects.equals(this.id, apiConfigData.id) &&
        Objects.equals(this.log, apiConfigData.log) &&
        Objects.equals(this.metrics, apiConfigData.metrics) &&
        Objects.equals(this.name, apiConfigData.name) &&
        Objects.equals(this.playout, apiConfigData.playout) &&
        Objects.equals(this.router, apiConfigData.router) &&
        Objects.equals(this.rtmp, apiConfigData.rtmp) &&
        Objects.equals(this.service, apiConfigData.service) &&
        Objects.equals(this.sessions, apiConfigData.sessions) &&
        Objects.equals(this.storage, apiConfigData.storage) &&
        Objects.equals(this.tls, apiConfigData.tls) &&
        Objects.equals(this.updateCheck, apiConfigData.updateCheck) &&
        Objects.equals(this.version, apiConfigData.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, api, createdAt, db, debug, ffmpeg, host, id, log, metrics, name, playout, router, rtmp, service, sessions, storage, tls, updateCheck, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiConfigData {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    api: ").append(toIndentedString(api)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    db: ").append(toIndentedString(db)).append("\n");
    sb.append("    debug: ").append(toIndentedString(debug)).append("\n");
    sb.append("    ffmpeg: ").append(toIndentedString(ffmpeg)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    playout: ").append(toIndentedString(playout)).append("\n");
    sb.append("    router: ").append(toIndentedString(router)).append("\n");
    sb.append("    rtmp: ").append(toIndentedString(rtmp)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    updateCheck: ").append(toIndentedString(updateCheck)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

