/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiConfigData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiConfig {
  @SerializedName("config")
  private ApiConfigData config = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("loaded_at")
  private String loadedAt = null;

  @SerializedName("overrides")
  private List<String> overrides = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public ApiConfig config(ApiConfigData config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(value = "")
  public ApiConfigData getConfig() {
    return config;
  }

  public void setConfig(ApiConfigData config) {
    this.config = config;
  }

  public ApiConfig createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ApiConfig loadedAt(String loadedAt) {
    this.loadedAt = loadedAt;
    return this;
  }

   /**
   * Get loadedAt
   * @return loadedAt
  **/
  @ApiModelProperty(value = "")
  public String getLoadedAt() {
    return loadedAt;
  }

  public void setLoadedAt(String loadedAt) {
    this.loadedAt = loadedAt;
  }

  public ApiConfig overrides(List<String> overrides) {
    this.overrides = overrides;
    return this;
  }

  public ApiConfig addOverridesItem(String overridesItem) {
    if (this.overrides == null) {
      this.overrides = new ArrayList<String>();
    }
    this.overrides.add(overridesItem);
    return this;
  }

   /**
   * Get overrides
   * @return overrides
  **/
  @ApiModelProperty(value = "")
  public List<String> getOverrides() {
    return overrides;
  }

  public void setOverrides(List<String> overrides) {
    this.overrides = overrides;
  }

  public ApiConfig updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiConfig apiConfig = (ApiConfig) o;
    return Objects.equals(this.config, apiConfig.config) &&
        Objects.equals(this.createdAt, apiConfig.createdAt) &&
        Objects.equals(this.loadedAt, apiConfig.loadedAt) &&
        Objects.equals(this.overrides, apiConfig.overrides) &&
        Objects.equals(this.updatedAt, apiConfig.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, createdAt, loadedAt, overrides, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiConfig {\n");
    
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    loadedAt: ").append(toIndentedString(loadedAt)).append("\n");
    sb.append("    overrides: ").append(toIndentedString(overrides)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

