/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiMetricsResponseMetric;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiMetricsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiMetricsResponse {
  @SerializedName("interval_sec")
  private Integer intervalSec = null;

  @SerializedName("metrics")
  private List<ApiMetricsResponseMetric> metrics = null;

  @SerializedName("timerange_sec")
  private Integer timerangeSec = null;

  public ApiMetricsResponse intervalSec(Integer intervalSec) {
    this.intervalSec = intervalSec;
    return this;
  }

   /**
   * Get intervalSec
   * @return intervalSec
  **/
  @ApiModelProperty(value = "")
  public Integer getIntervalSec() {
    return intervalSec;
  }

  public void setIntervalSec(Integer intervalSec) {
    this.intervalSec = intervalSec;
  }

  public ApiMetricsResponse metrics(List<ApiMetricsResponseMetric> metrics) {
    this.metrics = metrics;
    return this;
  }

  public ApiMetricsResponse addMetricsItem(ApiMetricsResponseMetric metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<ApiMetricsResponseMetric>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public List<ApiMetricsResponseMetric> getMetrics() {
    return metrics;
  }

  public void setMetrics(List<ApiMetricsResponseMetric> metrics) {
    this.metrics = metrics;
  }

  public ApiMetricsResponse timerangeSec(Integer timerangeSec) {
    this.timerangeSec = timerangeSec;
    return this;
  }

   /**
   * Get timerangeSec
   * @return timerangeSec
  **/
  @ApiModelProperty(value = "")
  public Integer getTimerangeSec() {
    return timerangeSec;
  }

  public void setTimerangeSec(Integer timerangeSec) {
    this.timerangeSec = timerangeSec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiMetricsResponse apiMetricsResponse = (ApiMetricsResponse) o;
    return Objects.equals(this.intervalSec, apiMetricsResponse.intervalSec) &&
        Objects.equals(this.metrics, apiMetricsResponse.metrics) &&
        Objects.equals(this.timerangeSec, apiMetricsResponse.timerangeSec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intervalSec, metrics, timerangeSec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiMetricsResponse {\n");
    
    sb.append("    intervalSec: ").append(toIndentedString(intervalSec)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    timerangeSec: ").append(toIndentedString(timerangeSec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

