/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ApiProcessConfigLimits
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProcessConfigLimits {
  @SerializedName("cpu_usage")
  private BigDecimal cpuUsage = null;

  @SerializedName("memory_mbytes")
  private Integer memoryMbytes = null;

  @SerializedName("waitfor_seconds")
  private Integer waitforSeconds = null;

  public ApiProcessConfigLimits cpuUsage(BigDecimal cpuUsage) {
    this.cpuUsage = cpuUsage;
    return this;
  }

   /**
   * Get cpuUsage
   * @return cpuUsage
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCpuUsage() {
    return cpuUsage;
  }

  public void setCpuUsage(BigDecimal cpuUsage) {
    this.cpuUsage = cpuUsage;
  }

  public ApiProcessConfigLimits memoryMbytes(Integer memoryMbytes) {
    this.memoryMbytes = memoryMbytes;
    return this;
  }

   /**
   * Get memoryMbytes
   * @return memoryMbytes
  **/
  @ApiModelProperty(value = "")
  public Integer getMemoryMbytes() {
    return memoryMbytes;
  }

  public void setMemoryMbytes(Integer memoryMbytes) {
    this.memoryMbytes = memoryMbytes;
  }

  public ApiProcessConfigLimits waitforSeconds(Integer waitforSeconds) {
    this.waitforSeconds = waitforSeconds;
    return this;
  }

   /**
   * Get waitforSeconds
   * @return waitforSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getWaitforSeconds() {
    return waitforSeconds;
  }

  public void setWaitforSeconds(Integer waitforSeconds) {
    this.waitforSeconds = waitforSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProcessConfigLimits apiProcessConfigLimits = (ApiProcessConfigLimits) o;
    return Objects.equals(this.cpuUsage, apiProcessConfigLimits.cpuUsage) &&
        Objects.equals(this.memoryMbytes, apiProcessConfigLimits.memoryMbytes) &&
        Objects.equals(this.waitforSeconds, apiProcessConfigLimits.waitforSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpuUsage, memoryMbytes, waitforSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProcessConfigLimits {\n");
    
    sb.append("    cpuUsage: ").append(toIndentedString(cpuUsage)).append("\n");
    sb.append("    memoryMbytes: ").append(toIndentedString(memoryMbytes)).append("\n");
    sb.append("    waitforSeconds: ").append(toIndentedString(waitforSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

