/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiProcessConfig;
import io.swagger.client.model.ApiProcessReport;
import io.swagger.client.model.ApiProcessState;
import java.io.IOException;

/**
 * ApiProcess
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProcess {
  @SerializedName("config")
  private ApiProcessConfig config = null;

  @SerializedName("created_at")
  private Integer createdAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("metadata")
  private Object metadata = null;

  @SerializedName("reference")
  private String reference = null;

  @SerializedName("report")
  private ApiProcessReport report = null;

  @SerializedName("state")
  private ApiProcessState state = null;

  @SerializedName("type")
  private String type = null;

  public ApiProcess config(ApiProcessConfig config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(value = "")
  public ApiProcessConfig getConfig() {
    return config;
  }

  public void setConfig(ApiProcessConfig config) {
    this.config = config;
  }

  public ApiProcess createdAt(Integer createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  public ApiProcess id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiProcess metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public ApiProcess reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public ApiProcess report(ApiProcessReport report) {
    this.report = report;
    return this;
  }

   /**
   * Get report
   * @return report
  **/
  @ApiModelProperty(value = "")
  public ApiProcessReport getReport() {
    return report;
  }

  public void setReport(ApiProcessReport report) {
    this.report = report;
  }

  public ApiProcess state(ApiProcessState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public ApiProcessState getState() {
    return state;
  }

  public void setState(ApiProcessState state) {
    this.state = state;
  }

  public ApiProcess type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProcess apiProcess = (ApiProcess) o;
    return Objects.equals(this.config, apiProcess.config) &&
        Objects.equals(this.createdAt, apiProcess.createdAt) &&
        Objects.equals(this.id, apiProcess.id) &&
        Objects.equals(this.metadata, apiProcess.metadata) &&
        Objects.equals(this.reference, apiProcess.reference) &&
        Objects.equals(this.report, apiProcess.report) &&
        Objects.equals(this.state, apiProcess.state) &&
        Objects.equals(this.type, apiProcess.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, createdAt, id, metadata, reference, report, state, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProcess {\n");
    
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    report: ").append(toIndentedString(report)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

