/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiPlayoutStatusSwap
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiPlayoutStatusSwap {
  @SerializedName("lasterror")
  private String lasterror = null;

  @SerializedName("lasturl")
  private String lasturl = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("url")
  private String url = null;

  public ApiPlayoutStatusSwap lasterror(String lasterror) {
    this.lasterror = lasterror;
    return this;
  }

   /**
   * Get lasterror
   * @return lasterror
  **/
  @ApiModelProperty(value = "")
  public String getLasterror() {
    return lasterror;
  }

  public void setLasterror(String lasterror) {
    this.lasterror = lasterror;
  }

  public ApiPlayoutStatusSwap lasturl(String lasturl) {
    this.lasturl = lasturl;
    return this;
  }

   /**
   * Get lasturl
   * @return lasturl
  **/
  @ApiModelProperty(value = "")
  public String getLasturl() {
    return lasturl;
  }

  public void setLasturl(String lasturl) {
    this.lasturl = lasturl;
  }

  public ApiPlayoutStatusSwap status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ApiPlayoutStatusSwap url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiPlayoutStatusSwap apiPlayoutStatusSwap = (ApiPlayoutStatusSwap) o;
    return Objects.equals(this.lasterror, apiPlayoutStatusSwap.lasterror) &&
        Objects.equals(this.lasturl, apiPlayoutStatusSwap.lasturl) &&
        Objects.equals(this.status, apiPlayoutStatusSwap.status) &&
        Objects.equals(this.url, apiPlayoutStatusSwap.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lasterror, lasturl, status, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiPlayoutStatusSwap {\n");
    
    sb.append("    lasterror: ").append(toIndentedString(lasterror)).append("\n");
    sb.append("    lasturl: ").append(toIndentedString(lasturl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

