/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiProcessConfigIOCleanup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProcessConfigIOCleanup {
  @SerializedName("max_file_age_seconds")
  private Integer maxFileAgeSeconds = null;

  @SerializedName("max_files")
  private Integer maxFiles = null;

  @SerializedName("pattern")
  private String pattern = null;

  @SerializedName("purge_on_delete")
  private Boolean purgeOnDelete = null;

  public ApiProcessConfigIOCleanup maxFileAgeSeconds(Integer maxFileAgeSeconds) {
    this.maxFileAgeSeconds = maxFileAgeSeconds;
    return this;
  }

   /**
   * Get maxFileAgeSeconds
   * @return maxFileAgeSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxFileAgeSeconds() {
    return maxFileAgeSeconds;
  }

  public void setMaxFileAgeSeconds(Integer maxFileAgeSeconds) {
    this.maxFileAgeSeconds = maxFileAgeSeconds;
  }

  public ApiProcessConfigIOCleanup maxFiles(Integer maxFiles) {
    this.maxFiles = maxFiles;
    return this;
  }

   /**
   * Get maxFiles
   * @return maxFiles
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxFiles() {
    return maxFiles;
  }

  public void setMaxFiles(Integer maxFiles) {
    this.maxFiles = maxFiles;
  }

  public ApiProcessConfigIOCleanup pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }

  public ApiProcessConfigIOCleanup purgeOnDelete(Boolean purgeOnDelete) {
    this.purgeOnDelete = purgeOnDelete;
    return this;
  }

   /**
   * Get purgeOnDelete
   * @return purgeOnDelete
  **/
  @ApiModelProperty(value = "")
  public Boolean isPurgeOnDelete() {
    return purgeOnDelete;
  }

  public void setPurgeOnDelete(Boolean purgeOnDelete) {
    this.purgeOnDelete = purgeOnDelete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProcessConfigIOCleanup apiProcessConfigIOCleanup = (ApiProcessConfigIOCleanup) o;
    return Objects.equals(this.maxFileAgeSeconds, apiProcessConfigIOCleanup.maxFileAgeSeconds) &&
        Objects.equals(this.maxFiles, apiProcessConfigIOCleanup.maxFiles) &&
        Objects.equals(this.pattern, apiProcessConfigIOCleanup.pattern) &&
        Objects.equals(this.purgeOnDelete, apiProcessConfigIOCleanup.purgeOnDelete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxFileAgeSeconds, maxFiles, pattern, purgeOnDelete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProcessConfigIOCleanup {\n");
    
    sb.append("    maxFileAgeSeconds: ").append(toIndentedString(maxFileAgeSeconds)).append("\n");
    sb.append("    maxFiles: ").append(toIndentedString(maxFiles)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    purgeOnDelete: ").append(toIndentedString(purgeOnDelete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

