/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiAVstream;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ApiProgressIO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProgressIO {
  @SerializedName("address")
  private String address = null;

  @SerializedName("avstream")
  private ApiAVstream avstream = null;

  @SerializedName("bitrate_kbit")
  private BigDecimal bitrateKbit = null;

  @SerializedName("channels")
  private Integer channels = null;

  @SerializedName("codec")
  private String codec = null;

  @SerializedName("coder")
  private String coder = null;

  @SerializedName("format")
  private String format = null;

  @SerializedName("fps")
  private BigDecimal fps = null;

  @SerializedName("frame")
  private Integer frame = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("index")
  private Integer index = null;

  @SerializedName("layout")
  private String layout = null;

  @SerializedName("packet")
  private Integer packet = null;

  @SerializedName("pix_fmt")
  private String pixFmt = null;

  @SerializedName("pps")
  private BigDecimal pps = null;

  @SerializedName("q")
  private BigDecimal q = null;

  @SerializedName("sampling_hz")
  private Integer samplingHz = null;

  @SerializedName("size_kb")
  private Integer sizeKb = null;

  @SerializedName("stream")
  private Integer stream = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("width")
  private Integer width = null;

  public ApiProgressIO address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ApiProgressIO avstream(ApiAVstream avstream) {
    this.avstream = avstream;
    return this;
  }

   /**
   * avstream
   * @return avstream
  **/
  @ApiModelProperty(value = "avstream")
  public ApiAVstream getAvstream() {
    return avstream;
  }

  public void setAvstream(ApiAVstream avstream) {
    this.avstream = avstream;
  }

  public ApiProgressIO bitrateKbit(BigDecimal bitrateKbit) {
    this.bitrateKbit = bitrateKbit;
    return this;
  }

   /**
   * kbit/s
   * @return bitrateKbit
  **/
  @ApiModelProperty(value = "kbit/s")
  public BigDecimal getBitrateKbit() {
    return bitrateKbit;
  }

  public void setBitrateKbit(BigDecimal bitrateKbit) {
    this.bitrateKbit = bitrateKbit;
  }

  public ApiProgressIO channels(Integer channels) {
    this.channels = channels;
    return this;
  }

   /**
   * Get channels
   * @return channels
  **/
  @ApiModelProperty(value = "")
  public Integer getChannels() {
    return channels;
  }

  public void setChannels(Integer channels) {
    this.channels = channels;
  }

  public ApiProgressIO codec(String codec) {
    this.codec = codec;
    return this;
  }

   /**
   * Get codec
   * @return codec
  **/
  @ApiModelProperty(value = "")
  public String getCodec() {
    return codec;
  }

  public void setCodec(String codec) {
    this.codec = codec;
  }

  public ApiProgressIO coder(String coder) {
    this.coder = coder;
    return this;
  }

   /**
   * Get coder
   * @return coder
  **/
  @ApiModelProperty(value = "")
  public String getCoder() {
    return coder;
  }

  public void setCoder(String coder) {
    this.coder = coder;
  }

  public ApiProgressIO format(String format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(value = "")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public ApiProgressIO fps(BigDecimal fps) {
    this.fps = fps;
    return this;
  }

   /**
   * Get fps
   * @return fps
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getFps() {
    return fps;
  }

  public void setFps(BigDecimal fps) {
    this.fps = fps;
  }

  public ApiProgressIO frame(Integer frame) {
    this.frame = frame;
    return this;
  }

   /**
   * Get frame
   * @return frame
  **/
  @ApiModelProperty(value = "")
  public Integer getFrame() {
    return frame;
  }

  public void setFrame(Integer frame) {
    this.frame = frame;
  }

  public ApiProgressIO height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(value = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public ApiProgressIO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiProgressIO index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * General
   * @return index
  **/
  @ApiModelProperty(value = "General")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public ApiProgressIO layout(String layout) {
    this.layout = layout;
    return this;
  }

   /**
   * Get layout
   * @return layout
  **/
  @ApiModelProperty(value = "")
  public String getLayout() {
    return layout;
  }

  public void setLayout(String layout) {
    this.layout = layout;
  }

  public ApiProgressIO packet(Integer packet) {
    this.packet = packet;
    return this;
  }

   /**
   * Get packet
   * @return packet
  **/
  @ApiModelProperty(value = "")
  public Integer getPacket() {
    return packet;
  }

  public void setPacket(Integer packet) {
    this.packet = packet;
  }

  public ApiProgressIO pixFmt(String pixFmt) {
    this.pixFmt = pixFmt;
    return this;
  }

   /**
   * Video
   * @return pixFmt
  **/
  @ApiModelProperty(value = "Video")
  public String getPixFmt() {
    return pixFmt;
  }

  public void setPixFmt(String pixFmt) {
    this.pixFmt = pixFmt;
  }

  public ApiProgressIO pps(BigDecimal pps) {
    this.pps = pps;
    return this;
  }

   /**
   * Get pps
   * @return pps
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getPps() {
    return pps;
  }

  public void setPps(BigDecimal pps) {
    this.pps = pps;
  }

  public ApiProgressIO q(BigDecimal q) {
    this.q = q;
    return this;
  }

   /**
   * Get q
   * @return q
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getQ() {
    return q;
  }

  public void setQ(BigDecimal q) {
    this.q = q;
  }

  public ApiProgressIO samplingHz(Integer samplingHz) {
    this.samplingHz = samplingHz;
    return this;
  }

   /**
   * Audio
   * @return samplingHz
  **/
  @ApiModelProperty(value = "Audio")
  public Integer getSamplingHz() {
    return samplingHz;
  }

  public void setSamplingHz(Integer samplingHz) {
    this.samplingHz = samplingHz;
  }

  public ApiProgressIO sizeKb(Integer sizeKb) {
    this.sizeKb = sizeKb;
    return this;
  }

   /**
   * kbytes
   * @return sizeKb
  **/
  @ApiModelProperty(value = "kbytes")
  public Integer getSizeKb() {
    return sizeKb;
  }

  public void setSizeKb(Integer sizeKb) {
    this.sizeKb = sizeKb;
  }

  public ApiProgressIO stream(Integer stream) {
    this.stream = stream;
    return this;
  }

   /**
   * Get stream
   * @return stream
  **/
  @ApiModelProperty(value = "")
  public Integer getStream() {
    return stream;
  }

  public void setStream(Integer stream) {
    this.stream = stream;
  }

  public ApiProgressIO type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ApiProgressIO width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(value = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProgressIO apiProgressIO = (ApiProgressIO) o;
    return Objects.equals(this.address, apiProgressIO.address) &&
        Objects.equals(this.avstream, apiProgressIO.avstream) &&
        Objects.equals(this.bitrateKbit, apiProgressIO.bitrateKbit) &&
        Objects.equals(this.channels, apiProgressIO.channels) &&
        Objects.equals(this.codec, apiProgressIO.codec) &&
        Objects.equals(this.coder, apiProgressIO.coder) &&
        Objects.equals(this.format, apiProgressIO.format) &&
        Objects.equals(this.fps, apiProgressIO.fps) &&
        Objects.equals(this.frame, apiProgressIO.frame) &&
        Objects.equals(this.height, apiProgressIO.height) &&
        Objects.equals(this.id, apiProgressIO.id) &&
        Objects.equals(this.index, apiProgressIO.index) &&
        Objects.equals(this.layout, apiProgressIO.layout) &&
        Objects.equals(this.packet, apiProgressIO.packet) &&
        Objects.equals(this.pixFmt, apiProgressIO.pixFmt) &&
        Objects.equals(this.pps, apiProgressIO.pps) &&
        Objects.equals(this.q, apiProgressIO.q) &&
        Objects.equals(this.samplingHz, apiProgressIO.samplingHz) &&
        Objects.equals(this.sizeKb, apiProgressIO.sizeKb) &&
        Objects.equals(this.stream, apiProgressIO.stream) &&
        Objects.equals(this.type, apiProgressIO.type) &&
        Objects.equals(this.width, apiProgressIO.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, avstream, bitrateKbit, channels, codec, coder, format, fps, frame, height, id, index, layout, packet, pixFmt, pps, q, samplingHz, sizeKb, stream, type, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProgressIO {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    avstream: ").append(toIndentedString(avstream)).append("\n");
    sb.append("    bitrateKbit: ").append(toIndentedString(bitrateKbit)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    codec: ").append(toIndentedString(codec)).append("\n");
    sb.append("    coder: ").append(toIndentedString(coder)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    fps: ").append(toIndentedString(fps)).append("\n");
    sb.append("    frame: ").append(toIndentedString(frame)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    layout: ").append(toIndentedString(layout)).append("\n");
    sb.append("    packet: ").append(toIndentedString(packet)).append("\n");
    sb.append("    pixFmt: ").append(toIndentedString(pixFmt)).append("\n");
    sb.append("    pps: ").append(toIndentedString(pps)).append("\n");
    sb.append("    q: ").append(toIndentedString(q)).append("\n");
    sb.append("    samplingHz: ").append(toIndentedString(samplingHz)).append("\n");
    sb.append("    sizeKb: ").append(toIndentedString(sizeKb)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

