/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiProcessReportHistoryEntry;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiProcessReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProcessReport {
  @SerializedName("created_at")
  private Integer createdAt = null;

  @SerializedName("history")
  private List<ApiProcessReportHistoryEntry> history = null;

  @SerializedName("log")
  private List<List<String>> log = null;

  @SerializedName("prelude")
  private List<String> prelude = null;

  public ApiProcessReport createdAt(Integer createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  public ApiProcessReport history(List<ApiProcessReportHistoryEntry> history) {
    this.history = history;
    return this;
  }

  public ApiProcessReport addHistoryItem(ApiProcessReportHistoryEntry historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<ApiProcessReportHistoryEntry>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/
  @ApiModelProperty(value = "")
  public List<ApiProcessReportHistoryEntry> getHistory() {
    return history;
  }

  public void setHistory(List<ApiProcessReportHistoryEntry> history) {
    this.history = history;
  }

  public ApiProcessReport log(List<List<String>> log) {
    this.log = log;
    return this;
  }

  public ApiProcessReport addLogItem(List<String> logItem) {
    if (this.log == null) {
      this.log = new ArrayList<List<String>>();
    }
    this.log.add(logItem);
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  @ApiModelProperty(value = "")
  public List<List<String>> getLog() {
    return log;
  }

  public void setLog(List<List<String>> log) {
    this.log = log;
  }

  public ApiProcessReport prelude(List<String> prelude) {
    this.prelude = prelude;
    return this;
  }

  public ApiProcessReport addPreludeItem(String preludeItem) {
    if (this.prelude == null) {
      this.prelude = new ArrayList<String>();
    }
    this.prelude.add(preludeItem);
    return this;
  }

   /**
   * Get prelude
   * @return prelude
  **/
  @ApiModelProperty(value = "")
  public List<String> getPrelude() {
    return prelude;
  }

  public void setPrelude(List<String> prelude) {
    this.prelude = prelude;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProcessReport apiProcessReport = (ApiProcessReport) o;
    return Objects.equals(this.createdAt, apiProcessReport.createdAt) &&
        Objects.equals(this.history, apiProcessReport.history) &&
        Objects.equals(this.log, apiProcessReport.log) &&
        Objects.equals(this.prelude, apiProcessReport.prelude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, history, log, prelude);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProcessReport {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    prelude: ").append(toIndentedString(prelude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

