/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiProbeIO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiProbe
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiProbe {
  @SerializedName("log")
  private List<String> log = null;

  @SerializedName("streams")
  private List<ApiProbeIO> streams = null;

  public ApiProbe log(List<String> log) {
    this.log = log;
    return this;
  }

  public ApiProbe addLogItem(String logItem) {
    if (this.log == null) {
      this.log = new ArrayList<String>();
    }
    this.log.add(logItem);
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  @ApiModelProperty(value = "")
  public List<String> getLog() {
    return log;
  }

  public void setLog(List<String> log) {
    this.log = log;
  }

  public ApiProbe streams(List<ApiProbeIO> streams) {
    this.streams = streams;
    return this;
  }

  public ApiProbe addStreamsItem(ApiProbeIO streamsItem) {
    if (this.streams == null) {
      this.streams = new ArrayList<ApiProbeIO>();
    }
    this.streams.add(streamsItem);
    return this;
  }

   /**
   * Get streams
   * @return streams
  **/
  @ApiModelProperty(value = "")
  public List<ApiProbeIO> getStreams() {
    return streams;
  }

  public void setStreams(List<ApiProbeIO> streams) {
    this.streams = streams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiProbe apiProbe = (ApiProbe) o;
    return Objects.equals(this.log, apiProbe.log) &&
        Objects.equals(this.streams, apiProbe.streams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(log, streams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiProbe {\n");
    
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    streams: ").append(toIndentedString(streams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

