/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiSessionStats;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ApiSessionPeers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSessionPeers {
  @SerializedName("local")
  private Map<String, ApiSessionStats> local = null;

  @SerializedName("sessions")
  private Integer sessions = null;

  @SerializedName("traffic_rx_mb")
  private Integer trafficRxMb = null;

  @SerializedName("traffic_tx_mb")
  private Integer trafficTxMb = null;

  public ApiSessionPeers local(Map<String, ApiSessionStats> local) {
    this.local = local;
    return this;
  }

  public ApiSessionPeers putLocalItem(String key, ApiSessionStats localItem) {
    if (this.local == null) {
      this.local = new HashMap<String, ApiSessionStats>();
    }
    this.local.put(key, localItem);
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  @ApiModelProperty(value = "")
  public Map<String, ApiSessionStats> getLocal() {
    return local;
  }

  public void setLocal(Map<String, ApiSessionStats> local) {
    this.local = local;
  }

  public ApiSessionPeers sessions(Integer sessions) {
    this.sessions = sessions;
    return this;
  }

   /**
   * Get sessions
   * @return sessions
  **/
  @ApiModelProperty(value = "")
  public Integer getSessions() {
    return sessions;
  }

  public void setSessions(Integer sessions) {
    this.sessions = sessions;
  }

  public ApiSessionPeers trafficRxMb(Integer trafficRxMb) {
    this.trafficRxMb = trafficRxMb;
    return this;
  }

   /**
   * Get trafficRxMb
   * @return trafficRxMb
  **/
  @ApiModelProperty(value = "")
  public Integer getTrafficRxMb() {
    return trafficRxMb;
  }

  public void setTrafficRxMb(Integer trafficRxMb) {
    this.trafficRxMb = trafficRxMb;
  }

  public ApiSessionPeers trafficTxMb(Integer trafficTxMb) {
    this.trafficTxMb = trafficTxMb;
    return this;
  }

   /**
   * Get trafficTxMb
   * @return trafficTxMb
  **/
  @ApiModelProperty(value = "")
  public Integer getTrafficTxMb() {
    return trafficTxMb;
  }

  public void setTrafficTxMb(Integer trafficTxMb) {
    this.trafficTxMb = trafficTxMb;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSessionPeers apiSessionPeers = (ApiSessionPeers) o;
    return Objects.equals(this.local, apiSessionPeers.local) &&
        Objects.equals(this.sessions, apiSessionPeers.sessions) &&
        Objects.equals(this.trafficRxMb, apiSessionPeers.trafficRxMb) &&
        Objects.equals(this.trafficTxMb, apiSessionPeers.trafficTxMb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(local, sessions, trafficRxMb, trafficTxMb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSessionPeers {\n");
    
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("    trafficRxMb: ").append(toIndentedString(trafficRxMb)).append("\n");
    sb.append("    trafficTxMb: ").append(toIndentedString(trafficTxMb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

