/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiSkillsLibrary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSkillsLibrary {
  @SerializedName("compiled")
  private String compiled = null;

  @SerializedName("linked")
  private String linked = null;

  @SerializedName("name")
  private String name = null;

  public ApiSkillsLibrary compiled(String compiled) {
    this.compiled = compiled;
    return this;
  }

   /**
   * Get compiled
   * @return compiled
  **/
  @ApiModelProperty(value = "")
  public String getCompiled() {
    return compiled;
  }

  public void setCompiled(String compiled) {
    this.compiled = compiled;
  }

  public ApiSkillsLibrary linked(String linked) {
    this.linked = linked;
    return this;
  }

   /**
   * Get linked
   * @return linked
  **/
  @ApiModelProperty(value = "")
  public String getLinked() {
    return linked;
  }

  public void setLinked(String linked) {
    this.linked = linked;
  }

  public ApiSkillsLibrary name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSkillsLibrary apiSkillsLibrary = (ApiSkillsLibrary) o;
    return Objects.equals(this.compiled, apiSkillsLibrary.compiled) &&
        Objects.equals(this.linked, apiSkillsLibrary.linked) &&
        Objects.equals(this.name, apiSkillsLibrary.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compiled, linked, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSkillsLibrary {\n");
    
    sb.append("    compiled: ").append(toIndentedString(compiled)).append("\n");
    sb.append("    linked: ").append(toIndentedString(linked)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

