/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiSession;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiSessionSummaryActive
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSessionSummaryActive {
  @SerializedName("bandwidth_rx_mbit")
  private BigDecimal bandwidthRxMbit = null;

  @SerializedName("bandwidth_tx_mbit")
  private BigDecimal bandwidthTxMbit = null;

  @SerializedName("list")
  private List<ApiSession> _list = null;

  @SerializedName("max_bandwidth_rx_mbit")
  private BigDecimal maxBandwidthRxMbit = null;

  @SerializedName("max_bandwidth_tx_mbit")
  private BigDecimal maxBandwidthTxMbit = null;

  @SerializedName("max_sessions")
  private Integer maxSessions = null;

  @SerializedName("sessions")
  private Integer sessions = null;

  public ApiSessionSummaryActive bandwidthRxMbit(BigDecimal bandwidthRxMbit) {
    this.bandwidthRxMbit = bandwidthRxMbit;
    return this;
  }

   /**
   * mbit/s
   * @return bandwidthRxMbit
  **/
  @ApiModelProperty(value = "mbit/s")
  public BigDecimal getBandwidthRxMbit() {
    return bandwidthRxMbit;
  }

  public void setBandwidthRxMbit(BigDecimal bandwidthRxMbit) {
    this.bandwidthRxMbit = bandwidthRxMbit;
  }

  public ApiSessionSummaryActive bandwidthTxMbit(BigDecimal bandwidthTxMbit) {
    this.bandwidthTxMbit = bandwidthTxMbit;
    return this;
  }

   /**
   * mbit/s
   * @return bandwidthTxMbit
  **/
  @ApiModelProperty(value = "mbit/s")
  public BigDecimal getBandwidthTxMbit() {
    return bandwidthTxMbit;
  }

  public void setBandwidthTxMbit(BigDecimal bandwidthTxMbit) {
    this.bandwidthTxMbit = bandwidthTxMbit;
  }

  public ApiSessionSummaryActive _list(List<ApiSession> _list) {
    this._list = _list;
    return this;
  }

  public ApiSessionSummaryActive addListItem(ApiSession _listItem) {
    if (this._list == null) {
      this._list = new ArrayList<ApiSession>();
    }
    this._list.add(_listItem);
    return this;
  }

   /**
   * Get _list
   * @return _list
  **/
  @ApiModelProperty(value = "")
  public List<ApiSession> getList() {
    return _list;
  }

  public void setList(List<ApiSession> _list) {
    this._list = _list;
  }

  public ApiSessionSummaryActive maxBandwidthRxMbit(BigDecimal maxBandwidthRxMbit) {
    this.maxBandwidthRxMbit = maxBandwidthRxMbit;
    return this;
  }

   /**
   * mbit/s
   * @return maxBandwidthRxMbit
  **/
  @ApiModelProperty(value = "mbit/s")
  public BigDecimal getMaxBandwidthRxMbit() {
    return maxBandwidthRxMbit;
  }

  public void setMaxBandwidthRxMbit(BigDecimal maxBandwidthRxMbit) {
    this.maxBandwidthRxMbit = maxBandwidthRxMbit;
  }

  public ApiSessionSummaryActive maxBandwidthTxMbit(BigDecimal maxBandwidthTxMbit) {
    this.maxBandwidthTxMbit = maxBandwidthTxMbit;
    return this;
  }

   /**
   * mbit/s
   * @return maxBandwidthTxMbit
  **/
  @ApiModelProperty(value = "mbit/s")
  public BigDecimal getMaxBandwidthTxMbit() {
    return maxBandwidthTxMbit;
  }

  public void setMaxBandwidthTxMbit(BigDecimal maxBandwidthTxMbit) {
    this.maxBandwidthTxMbit = maxBandwidthTxMbit;
  }

  public ApiSessionSummaryActive maxSessions(Integer maxSessions) {
    this.maxSessions = maxSessions;
    return this;
  }

   /**
   * Get maxSessions
   * @return maxSessions
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxSessions() {
    return maxSessions;
  }

  public void setMaxSessions(Integer maxSessions) {
    this.maxSessions = maxSessions;
  }

  public ApiSessionSummaryActive sessions(Integer sessions) {
    this.sessions = sessions;
    return this;
  }

   /**
   * Get sessions
   * @return sessions
  **/
  @ApiModelProperty(value = "")
  public Integer getSessions() {
    return sessions;
  }

  public void setSessions(Integer sessions) {
    this.sessions = sessions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSessionSummaryActive apiSessionSummaryActive = (ApiSessionSummaryActive) o;
    return Objects.equals(this.bandwidthRxMbit, apiSessionSummaryActive.bandwidthRxMbit) &&
        Objects.equals(this.bandwidthTxMbit, apiSessionSummaryActive.bandwidthTxMbit) &&
        Objects.equals(this._list, apiSessionSummaryActive._list) &&
        Objects.equals(this.maxBandwidthRxMbit, apiSessionSummaryActive.maxBandwidthRxMbit) &&
        Objects.equals(this.maxBandwidthTxMbit, apiSessionSummaryActive.maxBandwidthTxMbit) &&
        Objects.equals(this.maxSessions, apiSessionSummaryActive.maxSessions) &&
        Objects.equals(this.sessions, apiSessionSummaryActive.sessions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bandwidthRxMbit, bandwidthTxMbit, _list, maxBandwidthRxMbit, maxBandwidthTxMbit, maxSessions, sessions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSessionSummaryActive {\n");
    
    sb.append("    bandwidthRxMbit: ").append(toIndentedString(bandwidthRxMbit)).append("\n");
    sb.append("    bandwidthTxMbit: ").append(toIndentedString(bandwidthTxMbit)).append("\n");
    sb.append("    _list: ").append(toIndentedString(_list)).append("\n");
    sb.append("    maxBandwidthRxMbit: ").append(toIndentedString(maxBandwidthRxMbit)).append("\n");
    sb.append("    maxBandwidthTxMbit: ").append(toIndentedString(maxBandwidthTxMbit)).append("\n");
    sb.append("    maxSessions: ").append(toIndentedString(maxSessions)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

