/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiSkillsFilter;
import io.swagger.client.model.ApiSkillsHWAccel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiSkills
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSkills {
  @SerializedName("codecs")
  private Object codecs = null;

  @SerializedName("devices")
  private Object devices = null;

  @SerializedName("ffmpeg")
  private Object ffmpeg = null;

  @SerializedName("filter")
  private List<ApiSkillsFilter> filter = null;

  @SerializedName("formats")
  private Object formats = null;

  @SerializedName("hwaccels")
  private List<ApiSkillsHWAccel> hwaccels = null;

  @SerializedName("protocols")
  private Object protocols = null;

  public ApiSkills codecs(Object codecs) {
    this.codecs = codecs;
    return this;
  }

   /**
   * Get codecs
   * @return codecs
  **/
  @ApiModelProperty(value = "")
  public Object getCodecs() {
    return codecs;
  }

  public void setCodecs(Object codecs) {
    this.codecs = codecs;
  }

  public ApiSkills devices(Object devices) {
    this.devices = devices;
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/
  @ApiModelProperty(value = "")
  public Object getDevices() {
    return devices;
  }

  public void setDevices(Object devices) {
    this.devices = devices;
  }

  public ApiSkills ffmpeg(Object ffmpeg) {
    this.ffmpeg = ffmpeg;
    return this;
  }

   /**
   * Get ffmpeg
   * @return ffmpeg
  **/
  @ApiModelProperty(value = "")
  public Object getFfmpeg() {
    return ffmpeg;
  }

  public void setFfmpeg(Object ffmpeg) {
    this.ffmpeg = ffmpeg;
  }

  public ApiSkills filter(List<ApiSkillsFilter> filter) {
    this.filter = filter;
    return this;
  }

  public ApiSkills addFilterItem(ApiSkillsFilter filterItem) {
    if (this.filter == null) {
      this.filter = new ArrayList<ApiSkillsFilter>();
    }
    this.filter.add(filterItem);
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @ApiModelProperty(value = "")
  public List<ApiSkillsFilter> getFilter() {
    return filter;
  }

  public void setFilter(List<ApiSkillsFilter> filter) {
    this.filter = filter;
  }

  public ApiSkills formats(Object formats) {
    this.formats = formats;
    return this;
  }

   /**
   * Get formats
   * @return formats
  **/
  @ApiModelProperty(value = "")
  public Object getFormats() {
    return formats;
  }

  public void setFormats(Object formats) {
    this.formats = formats;
  }

  public ApiSkills hwaccels(List<ApiSkillsHWAccel> hwaccels) {
    this.hwaccels = hwaccels;
    return this;
  }

  public ApiSkills addHwaccelsItem(ApiSkillsHWAccel hwaccelsItem) {
    if (this.hwaccels == null) {
      this.hwaccels = new ArrayList<ApiSkillsHWAccel>();
    }
    this.hwaccels.add(hwaccelsItem);
    return this;
  }

   /**
   * Get hwaccels
   * @return hwaccels
  **/
  @ApiModelProperty(value = "")
  public List<ApiSkillsHWAccel> getHwaccels() {
    return hwaccels;
  }

  public void setHwaccels(List<ApiSkillsHWAccel> hwaccels) {
    this.hwaccels = hwaccels;
  }

  public ApiSkills protocols(Object protocols) {
    this.protocols = protocols;
    return this;
  }

   /**
   * Get protocols
   * @return protocols
  **/
  @ApiModelProperty(value = "")
  public Object getProtocols() {
    return protocols;
  }

  public void setProtocols(Object protocols) {
    this.protocols = protocols;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSkills apiSkills = (ApiSkills) o;
    return Objects.equals(this.codecs, apiSkills.codecs) &&
        Objects.equals(this.devices, apiSkills.devices) &&
        Objects.equals(this.ffmpeg, apiSkills.ffmpeg) &&
        Objects.equals(this.filter, apiSkills.filter) &&
        Objects.equals(this.formats, apiSkills.formats) &&
        Objects.equals(this.hwaccels, apiSkills.hwaccels) &&
        Objects.equals(this.protocols, apiSkills.protocols);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codecs, devices, ffmpeg, filter, formats, hwaccels, protocols);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSkills {\n");
    
    sb.append("    codecs: ").append(toIndentedString(codecs)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("    ffmpeg: ").append(toIndentedString(ffmpeg)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    formats: ").append(toIndentedString(formats)).append("\n");
    sb.append("    hwaccels: ").append(toIndentedString(hwaccels)).append("\n");
    sb.append("    protocols: ").append(toIndentedString(protocols)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

