/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ApiSkillsHWDevice;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiSkillsDevice
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSkillsDevice {
  @SerializedName("devices")
  private List<ApiSkillsHWDevice> devices = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  public ApiSkillsDevice devices(List<ApiSkillsHWDevice> devices) {
    this.devices = devices;
    return this;
  }

  public ApiSkillsDevice addDevicesItem(ApiSkillsHWDevice devicesItem) {
    if (this.devices == null) {
      this.devices = new ArrayList<ApiSkillsHWDevice>();
    }
    this.devices.add(devicesItem);
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/
  @ApiModelProperty(value = "")
  public List<ApiSkillsHWDevice> getDevices() {
    return devices;
  }

  public void setDevices(List<ApiSkillsHWDevice> devices) {
    this.devices = devices;
  }

  public ApiSkillsDevice id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiSkillsDevice name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSkillsDevice apiSkillsDevice = (ApiSkillsDevice) o;
    return Objects.equals(this.devices, apiSkillsDevice.devices) &&
        Objects.equals(this.id, apiSkillsDevice.id) &&
        Objects.equals(this.name, apiSkillsDevice.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devices, id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSkillsDevice {\n");
    
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

