/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ApiSession
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiSession {
  @SerializedName("bandwidth_rx_kbit")
  private BigDecimal bandwidthRxKbit = null;

  @SerializedName("bandwidth_tx_kbit")
  private BigDecimal bandwidthTxKbit = null;

  @SerializedName("bytes_rx")
  private Integer bytesRx = null;

  @SerializedName("bytes_tx")
  private Integer bytesTx = null;

  @SerializedName("created_at")
  private Integer createdAt = null;

  @SerializedName("extra")
  private String extra = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("local")
  private String local = null;

  @SerializedName("reference")
  private String reference = null;

  @SerializedName("remote")
  private String remote = null;

  public ApiSession bandwidthRxKbit(BigDecimal bandwidthRxKbit) {
    this.bandwidthRxKbit = bandwidthRxKbit;
    return this;
  }

   /**
   * kbit/s
   * @return bandwidthRxKbit
  **/
  @ApiModelProperty(value = "kbit/s")
  public BigDecimal getBandwidthRxKbit() {
    return bandwidthRxKbit;
  }

  public void setBandwidthRxKbit(BigDecimal bandwidthRxKbit) {
    this.bandwidthRxKbit = bandwidthRxKbit;
  }

  public ApiSession bandwidthTxKbit(BigDecimal bandwidthTxKbit) {
    this.bandwidthTxKbit = bandwidthTxKbit;
    return this;
  }

   /**
   * kbit/s
   * @return bandwidthTxKbit
  **/
  @ApiModelProperty(value = "kbit/s")
  public BigDecimal getBandwidthTxKbit() {
    return bandwidthTxKbit;
  }

  public void setBandwidthTxKbit(BigDecimal bandwidthTxKbit) {
    this.bandwidthTxKbit = bandwidthTxKbit;
  }

  public ApiSession bytesRx(Integer bytesRx) {
    this.bytesRx = bytesRx;
    return this;
  }

   /**
   * Get bytesRx
   * @return bytesRx
  **/
  @ApiModelProperty(value = "")
  public Integer getBytesRx() {
    return bytesRx;
  }

  public void setBytesRx(Integer bytesRx) {
    this.bytesRx = bytesRx;
  }

  public ApiSession bytesTx(Integer bytesTx) {
    this.bytesTx = bytesTx;
    return this;
  }

   /**
   * Get bytesTx
   * @return bytesTx
  **/
  @ApiModelProperty(value = "")
  public Integer getBytesTx() {
    return bytesTx;
  }

  public void setBytesTx(Integer bytesTx) {
    this.bytesTx = bytesTx;
  }

  public ApiSession createdAt(Integer createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  public ApiSession extra(String extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Get extra
   * @return extra
  **/
  @ApiModelProperty(value = "")
  public String getExtra() {
    return extra;
  }

  public void setExtra(String extra) {
    this.extra = extra;
  }

  public ApiSession id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiSession local(String local) {
    this.local = local;
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  @ApiModelProperty(value = "")
  public String getLocal() {
    return local;
  }

  public void setLocal(String local) {
    this.local = local;
  }

  public ApiSession reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public ApiSession remote(String remote) {
    this.remote = remote;
    return this;
  }

   /**
   * Get remote
   * @return remote
  **/
  @ApiModelProperty(value = "")
  public String getRemote() {
    return remote;
  }

  public void setRemote(String remote) {
    this.remote = remote;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiSession apiSession = (ApiSession) o;
    return Objects.equals(this.bandwidthRxKbit, apiSession.bandwidthRxKbit) &&
        Objects.equals(this.bandwidthTxKbit, apiSession.bandwidthTxKbit) &&
        Objects.equals(this.bytesRx, apiSession.bytesRx) &&
        Objects.equals(this.bytesTx, apiSession.bytesTx) &&
        Objects.equals(this.createdAt, apiSession.createdAt) &&
        Objects.equals(this.extra, apiSession.extra) &&
        Objects.equals(this.id, apiSession.id) &&
        Objects.equals(this.local, apiSession.local) &&
        Objects.equals(this.reference, apiSession.reference) &&
        Objects.equals(this.remote, apiSession.remote);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bandwidthRxKbit, bandwidthTxKbit, bytesRx, bytesTx, createdAt, extra, id, local, reference, remote);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiSession {\n");
    
    sb.append("    bandwidthRxKbit: ").append(toIndentedString(bandwidthRxKbit)).append("\n");
    sb.append("    bandwidthTxKbit: ").append(toIndentedString(bandwidthTxKbit)).append("\n");
    sb.append("    bytesRx: ").append(toIndentedString(bytesRx)).append("\n");
    sb.append("    bytesTx: ").append(toIndentedString(bytesTx)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    remote: ").append(toIndentedString(remote)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

