/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiVersion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiVersion {
  @SerializedName("arch")
  private String arch = null;

  @SerializedName("build_date")
  private String buildDate = null;

  @SerializedName("compiler")
  private String compiler = null;

  @SerializedName("number")
  private String number = null;

  @SerializedName("repository_branch")
  private String repositoryBranch = null;

  @SerializedName("repository_commit")
  private String repositoryCommit = null;

  public ApiVersion arch(String arch) {
    this.arch = arch;
    return this;
  }

   /**
   * Get arch
   * @return arch
  **/
  @ApiModelProperty(value = "")
  public String getArch() {
    return arch;
  }

  public void setArch(String arch) {
    this.arch = arch;
  }

  public ApiVersion buildDate(String buildDate) {
    this.buildDate = buildDate;
    return this;
  }

   /**
   * Get buildDate
   * @return buildDate
  **/
  @ApiModelProperty(value = "")
  public String getBuildDate() {
    return buildDate;
  }

  public void setBuildDate(String buildDate) {
    this.buildDate = buildDate;
  }

  public ApiVersion compiler(String compiler) {
    this.compiler = compiler;
    return this;
  }

   /**
   * Get compiler
   * @return compiler
  **/
  @ApiModelProperty(value = "")
  public String getCompiler() {
    return compiler;
  }

  public void setCompiler(String compiler) {
    this.compiler = compiler;
  }

  public ApiVersion number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public ApiVersion repositoryBranch(String repositoryBranch) {
    this.repositoryBranch = repositoryBranch;
    return this;
  }

   /**
   * Get repositoryBranch
   * @return repositoryBranch
  **/
  @ApiModelProperty(value = "")
  public String getRepositoryBranch() {
    return repositoryBranch;
  }

  public void setRepositoryBranch(String repositoryBranch) {
    this.repositoryBranch = repositoryBranch;
  }

  public ApiVersion repositoryCommit(String repositoryCommit) {
    this.repositoryCommit = repositoryCommit;
    return this;
  }

   /**
   * Get repositoryCommit
   * @return repositoryCommit
  **/
  @ApiModelProperty(value = "")
  public String getRepositoryCommit() {
    return repositoryCommit;
  }

  public void setRepositoryCommit(String repositoryCommit) {
    this.repositoryCommit = repositoryCommit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiVersion apiVersion = (ApiVersion) o;
    return Objects.equals(this.arch, apiVersion.arch) &&
        Objects.equals(this.buildDate, apiVersion.buildDate) &&
        Objects.equals(this.compiler, apiVersion.compiler) &&
        Objects.equals(this.number, apiVersion.number) &&
        Objects.equals(this.repositoryBranch, apiVersion.repositoryBranch) &&
        Objects.equals(this.repositoryCommit, apiVersion.repositoryCommit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arch, buildDate, compiler, number, repositoryBranch, repositoryCommit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiVersion {\n");
    
    sb.append("    arch: ").append(toIndentedString(arch)).append("\n");
    sb.append("    buildDate: ").append(toIndentedString(buildDate)).append("\n");
    sb.append("    compiler: ").append(toIndentedString(compiler)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    repositoryBranch: ").append(toIndentedString(repositoryBranch)).append("\n");
    sb.append("    repositoryCommit: ").append(toIndentedString(repositoryCommit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

