/*
 * datarhei Core API
 * Expose REST API for the datarhei Core
 *
 * OpenAPI spec version: 3.0
 * Contact: hello@datarhei.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApiWidgetProcess
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-20T09:54:33.803Z")
public class ApiWidgetProcess {
  @SerializedName("current_sessions")
  private Integer currentSessions = null;

  @SerializedName("total_sessions")
  private Integer totalSessions = null;

  @SerializedName("uptime")
  private Integer uptime = null;

  public ApiWidgetProcess currentSessions(Integer currentSessions) {
    this.currentSessions = currentSessions;
    return this;
  }

   /**
   * Get currentSessions
   * @return currentSessions
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrentSessions() {
    return currentSessions;
  }

  public void setCurrentSessions(Integer currentSessions) {
    this.currentSessions = currentSessions;
  }

  public ApiWidgetProcess totalSessions(Integer totalSessions) {
    this.totalSessions = totalSessions;
    return this;
  }

   /**
   * Get totalSessions
   * @return totalSessions
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalSessions() {
    return totalSessions;
  }

  public void setTotalSessions(Integer totalSessions) {
    this.totalSessions = totalSessions;
  }

  public ApiWidgetProcess uptime(Integer uptime) {
    this.uptime = uptime;
    return this;
  }

   /**
   * Get uptime
   * @return uptime
  **/
  @ApiModelProperty(value = "")
  public Integer getUptime() {
    return uptime;
  }

  public void setUptime(Integer uptime) {
    this.uptime = uptime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiWidgetProcess apiWidgetProcess = (ApiWidgetProcess) o;
    return Objects.equals(this.currentSessions, apiWidgetProcess.currentSessions) &&
        Objects.equals(this.totalSessions, apiWidgetProcess.totalSessions) &&
        Objects.equals(this.uptime, apiWidgetProcess.uptime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentSessions, totalSessions, uptime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiWidgetProcess {\n");
    
    sb.append("    currentSessions: ").append(toIndentedString(currentSessions)).append("\n");
    sb.append("    totalSessions: ").append(toIndentedString(totalSessions)).append("\n");
    sb.append("    uptime: ").append(toIndentedString(uptime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

